---
- name: "NVM | Install Node Version Manager (NVM)"
  ansible.builtin.shell:
    cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm"
  become: true

- name: "NPM | Install Latest LTS NodeJS version"
  ansible.builtin.shell:
    cmd: "nvm install --lts --latest-npm"
  become: true

- name: "NPM | Set Default LTS NodeJS version"
  ansible.builtin.shell:
    cmd: "nvm alias default lts/*"
  become: true
