---
- name: Check if path exists
  ansible.builtin.stat:
    path: "/usr/bin/atuin"
  register: atuin_path_check

- name: Download Atuin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh
    dest: /tmp/install.sh

- name: Install Atuin using install.sh script
  ansible.builtin.shell:
    cmd: '/tmp/install.sh'
  when: not atuin_path_check.stat.exists

- name: Atuin Remove the install.sh
  file:
    path: /tmp/install.sh
    state: absent

- name: Atuin | Copy Config
  ansible.builtin.file:
    path: "/{{ ansible_user_dir }}/.config/atuin"
    state: directory

- name: Copy Atuin config
  ansible.builtin.copy:
    src: config.toml
    dest: "/{{ ansible_user_dir }}/.config/atuin/config.toml"
