---
- name: "Bash | Copy .zshrc"
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"

- name: "Install Zsh and Oh-My-Zsh on macOS"
  homebrew:
    name: zsh
  become: true

- name: "Set Zsh as default shell on macOS"
  ansible.builtin.command:
    cmd: "chsh -s /usr/local/bin/zsh {{ host_user }}"
  become: true
