---

- name: "Install Zsh and Oh-My-Zsh on Ubuntu"
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Check if path exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: omzsh_path_check

- name: Install Oh-my-zsh
  ansible.builtin.shell:
    cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  when: not omzsh_path_check.stat.exists

- name: "Set Zsh as default shell on Ubuntu"
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh {{ host_user }}"
  become: true

- name: "Bash | Copy .zshrc"
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"


- name: "zsh | Copy Private Files openai.apikey"
  ansible.builtin.lineinfile:
    name: "~/.openai.apikey"
    line: "{{ OPENAI_KEY }}"
    create: true
    mode: "0600"
    state: present

- name: "zsh | Copy Private Files zshrc"
  ansible.builtin.lineinfile:
    name: "~/.zshrc"
    line: "export OPENAI_API_KEY='{{ OPENAI_API_KEY }}'"
    create: true
    mode: "0600"
    state: present


- name: "Bash | Add code PATH"
  ansible.builtin.lineinfile:
    name: "~/.zshrc"
    line: 'export PATH=$PATH:"/mnt/c/Users/{{ wsl_host_user }}/AppData/Local/Programs/Microsoft VS Code/bin"'
    create: true
    mode: "0600"
    state: present
  when: windows_user
