live_config_reload = true
[scrolling]
history = 100000

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[mouse.hints]
modifiers = "Command"

  [mouse.hints.launcher]
  program = "open"

[colors.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"S
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"
