live_config_reload = true
shell = "wsl -d ubuntu --cd ~"

[scrolling]
history = 100000

[font.normal]
family = "ComicCodeLigatures NF"
style = "Regular"

[font.bold]
family = "ComicCodeLigatures NF"
style = "Bold"

[font.italic]
family = "ComicCodeLigatures NF"
style = "Italic"

[font.bold_italic]
family = "ComicCodeLigatures NF"
style = "Bold Italic"

# [selection]
# save_to_clipboard = true

[colors.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"
