---
- name: "Git | Install"
  ansible.builtin.apt:
    name:
      - git
    state: latest
  become: true

- name: "Git | Set diff.colorMoved"
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: zebra

- name: "Git | Set fetch.prune"
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: true

# git config --global --add url."git@github.com:".insteadOf "https://github.com/"
# - name: "Git | Set URL to SSH"
#   community.general.git_config:
#     name: URL
#     scope: global
#     value: "git@github.com"

- name: "Git | Set init.defaultBranch"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main


- name: "Git | Set user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

- name: "Git | Set user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
    
- name: "GIT | Install better-commits"
  ansible.builtin.shell:
    cmd: "npm install -g better-commits"
  args:
    creates: "{{ ansible_env.HOME }}/.npm-global/bin/better-commits"
  become: true
  when: npm_check.rc == 0  # Only run if npm is installed

- name: "Add better-commits alias to zshrc or bashrc"
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: 'alias bc=better-commits'
    insertafter: '^# User configuration'
  when: "'zsh' in ansible_play_hosts[0] and not ansible_env.HOME == '/root' and npm_check.rc == 0"  # Add to zshrc only if user is not root and npm is installed

- name: "Add better-commits alias to bashrc"
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: 'alias bc=better-commits'
    insertafter: '^# User configuration'
  when: "'bash' in ansible_play_hosts[0] and not ansible_env.HOME == '/root' and npm_check.rc == 0"  # Add to bashrc only if user is not root and npm is installed
