---
- name: Install Ghostty (macOS)
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Ghostty | Install via Homebrew
      community.general.homebrew_cask:
        name: ghostty
        state: present
      ignore_errors: True

    - name: Ghostty | Create config directory
      file:
        path: "{{ ansible_user_dir }}/.config/ghostty"
        state: directory
        mode: '0755'

    - name: Ghostty | Copy configuration
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.config/ghostty/config"
        src: config.j2
        mode: 0644
