---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Run Mac Tasks
  ansible.builtin.import_tasks: mac.yml
   when: ansible_system == 'Darwin'