---
- name: Install Alacritty Repo
  ansible.builtin.apt_repository:
    repo: 'ppa:aslatter/ppa'
    state: present
- name: Install Alacritty on Debian
  ansible.builtin.package:
    name: alacritty
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "/{{ ansible_user_dir }}/.config"
    state: directory
  when: ansible_os_family == 'Debian'

- name: Copy Alacritty config
  ansible.builtin.copy:
    src: alacritty.yaml
    dest: "/{{ ansible_user_dir }}/.config/alacritty/alacritty.toml"
  when: ansible_os_family == 'Debian'
