---
- name: "1Password | Install 1Password"
  homebrew:
    name: 1password
    state: present
  become: true

- name: "1Password | Install 1Password CLI"
  homebrew:
    name: 1password-cli
    state: present
  become: true
