---

- name: "Fonts | Clone MonaSpace Fonts"
  ansible.builtin.git:
    repo: https://github.com/githubnext/monaspace.git
    dest: "{{ ansible_env.HOME }}/monaspace-fonts"

- name: Changing perm of "/tmp/install.sh", adding "u+x"
  file: dest={{ ansible_env.HOME }}/monaspace-fonts/util/install_macos.sh mode=u+x

- name: "Fonts | Install MonaSpace Fonts"
  ansible.builtin.shell:
    cmd: "{{ ansible_env.HOME }}/monaspace-fonts/util/install_macos.sh"
